canonical:  https://gematik.de/fhir/erp-eu/
fhirVersion: 4.0.1
applyExtensionMetadataToRoot: false
version: 1.1.0
id: de.gematik.erezept.eu
name: E-Rezept Workflow EU
title: "E-Rezept Workflow EU"
description: Dieser IG Beschreibt Datenmodelle f√ºr den E-Rezept-Fachdienst mit dem NCPeH Deutschland
status: active # draft | active | retired | unknown
copyrightYear: 2025+
releaseLabel: release # ci-build, ballot, release
jurisdiction: urn:iso:std:iso:3166#DE "Germany" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gematik GmbH
  url: https://gematik.de
  email: erp-umsetzung@gematik.de

dependencies:
  de.basisprofil.r4: 1.5.4
  de.gematik.epa.medication: 1.3.0
  de.gematik.terminology: 1.0.8
  de.gematik.ti: 1.2.0

menu:
  Start: index.html
  Inhaltsverzeichnis: toc.html
  FHIR-Artefakte: artifacts.html

parameters:
  path-pages:
    - input/content