canonical:  https://gematik.de/fhir/erp-eu/
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
status: draft
version: "1.0.0-beta"
dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.5.2
  de.gematik.fhir.directory: 0.11.25
  de.gematik.epa.medication: 1.0.5-1
  de.gematik.terminology: 1.0.5
  de.gematik.ti: 1.0.0