canonical:  https://gematik.de/fhir/erp-eu/
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
status: active
version: "1.0.0"
dependencies:
  de.basisprofil.r4: 1.5.3
  de.gematik.fhir.directory: 0.13.1
  de.gematik.epa.medication: 1.1.5
  de.gematik.terminology: 1.0.6
  de.gematik.ti: 1.1.0