canonical:  https://gematik.de/fhir/erp-eu/
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
status: draft
version: "1.0.0-beta"
dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.5.2
  de.gematik.terminology: 1.0.1  # TODO Downgrade
  de.gematik.epa.medication: 1.1.1 # TODO Downgrade
  de.gematik.erezept-workflow.r4: 1.5.0-beta #TODO Update wenn released, ggf. auch ePA Basic wenn Prescription Identifier in epaBasic geht